export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const CREATE_TAB = "CREATE_TAB";
export const DELETE_TAB = "DELETE_TAB";
export const LOAD_ROOMS_SUCCESS = "LOAD_ROOMS_SUCCESS";
export const SERVER_SEND_MESSAGE = 'SERVER_SEND_MESSAGE';
export const ADMIN_JOIN_ROOM = 'ADMIN_JOIN_ROOM';
export const ADMIN_JOIN_ROOM_SUCCESS = 'ADMIN_JOIN_ROOM_SUCCESS';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const ADD_NEW_ROOM = 'ADD_NEW_ROOM';
export const ADMIN_SEND_MESSAGE = "ADMIN_SEND_MESSAGE";
